### ISSUE TITLE
A way to specify approved values of attributes

### ISSUE THREAD

**Issue by jkcclemens** [notriddle/ammonia#100]
Hello! I'd like to bring #24 back up, since there was no resolution on whether actually allowing this more generally is "too heavy" for ammonia.

I would like to limit the types of `input` tags allowed in sanitised output. For example, in parsing GitHub-flavoured markdown, you can create checkboxes.

- [ ] Like this

This is the only acceptable value of `input[type]` for me, so being able to deny any other type would be really useful.

Can this reasonably be allowed in ammonia?

**Comment by notriddle** [comment]
Doesn't sound too heavy to me.

**Comment by jkcclemens** [comment]
🎉 To clarify, this would be generic in the sense you can whitelist any element's attributes to specific values, right? For example:

```
input
  type
    checkbox
a
  target
    _blank
    something_else
  title
    limited for some reason
```

**Comment by kashike** [comment]
Bump bump!
