### ISSUE TITLE
A way to specify approved *values* of attributes

### ISSUE THREAD

**Issue by carols10cents** [notriddle/ammonia#24]
Use case: I would like to allow syntax highlighting classes on `code` tags but not [arbitrary classes](https://github.com/ChALkeR/notes/blob/master/Improper-markup-sanitization.md). 

I'd be fine having this ability just for `class` attribute values, as [sanitize-html does](https://www.npmjs.com/package/sanitize-html#allowed-css-classes); not sure if there's a use case for values of any attribute or not.

**Comment by Eijebong** [comment]
We could change `tag_attributes` to be a `HashMap<&str, HashMap<&str, EitherValuesOrAll>>` which would be too heavy IMHO.

I think adding a `allowed_classes` argument as `HashMap<&str, HashSet<&str>>` is a better solution.
@notriddle How would you feel about that ?

**Comment by notriddle** [comment]
I don't have a problem with `allowed_classes`.

**Comment by Eijebong** [comment]
Ok 👍 

Doing it now then
