### ISSUE TITLE
Allow more general input types

### ISSUE THREAD

**Issue by lnicola** [notriddle/ammonia#38]
We might want to make `clean` work with something that's more general than `&str`, like `Read`.

See https://doc.servo.org/tendril/stream/trait.TendrilSink.html.

**Comment by notriddle** [comment]
SGTM

Only thing I'm concerned about is leaking tendril or html5ever into the public API. I want to be able to take a breaking upgrade to one of those libraries without having to release a breaking version of Ammonia.

**Comment by Eijebong** [comment]
I'm not sure this is what you were intending to do, but it would be nice to have `clean(&str)` and `clean_from_reader<T: Read>(T)` (not sure about that name) since &str isn't `Read`.
