### ISSUE TITLE
Allow more general output types

### ISSUE THREAD

**Issue by lnicola** [notriddle/ammonia#42]
Just like we did in #38, we might want to avoid a buffering step for the output. API proposal:

```rust
struct AmmoniaDocument(RcDom);

impl AmmoniaDocument {
    pub fn to_string(&self) -> String;
    pub fn write_to<W: Write>(&self, writer: &mut W);
    pub fn into_rcdom(self) -> RcDom; // or Handle? might be useful, but do we really want to?
}
```

Part of #31.

**Comment by notriddle** [comment]
> do we really want to?

Exposing RcDom means that every time html5ever makes a breaking change, so do we. I'd prefer if we were able to upgrade across non-compatible html5ever versions without making a non-compatible release ourselves, especially since the release after we're done with the libz blitz checklist is filled out is probably going to be **1.0**.

**Comment by lnicola** [comment]
> Exposing RcDom means that every time html5ever makes a breaking change, so do we.

Exactly.

I suppose having an `unstable` feature flag with enables that feature feels a bit hackish?

**Comment by notriddle** [comment]
If we're going to do that, we'll do it [like rayon does it]. It is not okay for a deep dependency to activate the unstable features.

[like rayon does it]: https://github.com/nikomatsakis/rayon#semver-policy-the-rayon-core-crate-and-unstable-features

**Comment by lnicola** [comment]
Oh yeah, that seems fair.

**Comment by lnicola** [comment]
But still, forcing transitive (indirect) dependencies of `ammonia` to do that seems a bit heavy-handed.

**Comment by notriddle** [comment]
I'd rather have the unstable interfaces only be used by apps, which can use a lockfile to directly specify the version of all dependencies. You need a lockfile in order to be sure that your html5ever and ammonia versions line up, and libraries don't have lockfiles.
