### ISSUE TITLE
Custom UrlRelative policy

### ISSUE THREAD

**Issue by lnicola** [notriddle/ammonia#47]
It might be useful to have a `UrlRelative::Evaluate(Box<Fn(String) -> Option<String>>)` (or `FnMut`), where the function gets passed the previous URL and returns a new one. This allows the caller to do custom sanitization or rewriting of the URLs without going through `to_dom_node`.

Do we want to implement something like this?

**Comment by lnicola** [comment]
Another useful feature would be regex filtering. We should check what other libraries offer.

Via https://www.reddit.com/r/rust/comments/72kp3c/ammonia_100rc1_an_html_sanitization_crate/dnjdxpn/.

**Comment by ssokolow** [comment]
Here's what's offered by the libraries I'd trust:

* [lxml.html.clean.Cleaner](http://lxml.de/api/lxml.html.clean.Cleaner-class.html) (Python)
    * Called on a pre-parsed DOM after you've asked LXML to parse it and mutates it in place.
    * It doesn't directly offer this functionality, but it's part of LXML, so you're guaranteed the ability to use XPath or the ElementTree API's subset of it to mutably iterate through all DOM nodes with an `href` or `src` attribute either before or after calling the cleaner and the XPath and DOM are backed by libxml's C implementation.
* Bleach (Python):
  * https://bleach.readthedocs.io/en/latest/clean.html#allowed-protocols-protocols
  * https://bleach.readthedocs.io/en/latest/clean.html#html5lib-filters-filters
* [html5lib.filters.sanitizer](https://html5lib.readthedocs.io/en/latest/html5lib.filters.html#html5lib.filters.sanitizer.Filter) (Python)
  * It's a filter which you can chain up before or after a filter which modifies URLs.
* [DOMPurify](https://github.com/cure53/DOMPurify) (JavaScript: Browsers and Node.JS):
  * `ALLOWED_URI_REGEXP`
  * `DOMPurify.addHook` (with various events like `afterSanitizeAttributes`)
* HTML Purifier for PHP:
  * http://htmlpurifier.org/live/configdoc/plain.html#URI
  * http://htmlpurifier.org/docs/enduser-uri-filter.html

**Comment by lnicola** [comment]
> Allowed protocols (protocols)

Should be possible with https://github.com/notriddle/ammonia/blob/master/src/lib.rs#L312

> html5lib Filters (filters)

This is a hard one. We already expose the DOM via a heavily hidden method: https://github.com/notriddle/ammonia/blob/master/src/lib.rs#L828, but the users will never find it.

> html5lib.filters.sanitizer

Not sure about this.

> `ALLOWED_URI_REGEXP`

That would be the current issue.

> `DOMPurify.addHook`

We have nothing like this.

> http://htmlpurifier.org/live/configdoc/plain.html#URI

We could steal something from there. But that whole page is... humbling.

**Comment by lnicola** [comment]
I tried to implement this, but I'm not sure how to make the compiler happy about `UrlRelative` having a function inside. If anyone else wants to take this... 😄.

**Comment by lnicola** [comment]
I think we want this to apply to absolute URLs, too.

**Comment by notriddle** [comment]
No, I think we want there to be a separate policy for full-blown URL checking. Separation of concerns: resolving relative URLs is not connected with checking whether any particular URL should be allowed or not.
