### ISSUE TITLE
Better document the defaults

### ISSUE THREAD

**Issue by lnicola** [notriddle/ammonia#55]
Almost nothing says what `link_rel` is set to by default, but this applies to all configuration setters.

Courtesy of https://www.reddit.com/r/rust/comments/72kp3c/ammonia_100rc1_an_html_sanitization_crate/dnjdxpn/.

**Comment by ssokolow** [comment]
Not only that, it should really say the default in the place people wind up when they go looking for that specific setter... ie, the documentation for the setter itself.

**Comment by lnicola** [comment]
Yes, that's what I meant. The defaults should be described in the setter documentation, even if it might mean duplicating them.
