### ISSUE TITLE
Semi-relative rewriting (enhancement)

### ISSUE THREAD

**Issue by therealbstern** [notriddle/ammonia#69]
The url_relative: UrlRelative::RewriteWithBase(base) option requires that base include the "http(s)://hostname.com/" part, or it will panic when parsing the URL.  There is another desirable sort of URL rewriting that I have come across in practice:

Rewrite `foo` to (some prefix) + `/foo`.  This means that in a page with a link to `foo`, no matter how deep in the document tree it is, it will always go to the same place.

Right now, it does not appear to me how to tell a page with the URL http://example.com/a/b/c/testing that contains a relative link to `foo`, `bar`, and `baz/quux` to send them to, respectively, http://example.com/a/foo, http://example.com/a/bar, and http://example.com/a/baz/quux.

Am I missing something?

**Comment by therealbstern** [comment]
A closure for specifying how to rewrite might be a portable way around this.

**Comment by notriddle** [comment]
You could do it with the [custom](https://github.com/notriddle/ammonia/blob/6261a523637db14af3cf35d96820edffd9f09ada/src/lib.rs#L1289) mode.

**Comment by therealbstern** [comment]
Thank you, I must have been looking at the wrong version of the docs!

**Comment by notriddle** [comment]
Yup, that'll be fixed once 1.0-rc2 is released.
