### ISSUE TITLE
Add method for removing tag contents

### ISSUE THREAD

**Issue by mattico** [notriddle/ammonia#89]
I'd like to be able to take an HTML snippet and remove everything that isn't plain text. This includes things like the contents of `<script>` and `<style>` tags. Essentially:

```rust
assert_eq!(ammonia::clean(r"
<script type='text/javascript'>XSS</script>
Some <em>text</em> here!
<style>a { font-size: 14px; }</style>
"), "Some text here!");
```

I'm willing to make a PR for this, but I don't know how the API should look. `Builder::remove_content_tags()`?

**Comment by notriddle** [comment]
Sounds good to me.
