### ISSUE TITLE
Elements with non-whitelisted attributes get dropped

### ISSUE THREAD

**Issue by lnicola** [notriddle/ammonia#9]
```rust
extern crate ammonia;

fn main() {
    println!("{}", ammonia::clean(r#"<table><tr></tr></table>"#)); // => "<table><tr></tr></table>
"
    println!("{}", ammonia::clean(r#"<table id="bar"><tr></tr></table>"#)); // => "<tr></tr>"
}
```

Is this expected?

Update: I believe this happens because `id` is not a whitelisted attribute. I thought that only the attribute would get removed, not the whole element. The real-world case where I encountered this was `<table border=1>`.

**Comment by notriddle** [comment]
It's expected, though perhaps it is undesirable.

**Comment by lnicola** [comment]
Yeah, I've seen why it happenes. It's easy to fix, but the test suite must be updated. The only one that gives dubious results is `test_100`, which yields:

```html
<a href="http://harmless.com/This is still inside the comment: --evadefilter><img onerror=alert(100) src=''/><a href=">link</a>
```

Which is actually more harmless than it looks, as the `onerror` attribute ends up in the `href`.  It looks like the test and `html5ever` have different ideas about how comments work.

I can submit a PR, but I see why you might not want this change.

**Comment by notriddle** [comment]
You can just remove that test. What ammonia really needs is a harness to just run that sanitizer test bed instead of me hand-picking a couple of "hard-looking" tests.

**Comment by lnicola** [comment]
Thanks! I'm not sure what the bots are doing, but this can be closed, right?
