### ISSUE TITLE
Please release 1.0.2 on crates.io

### ISSUE THREAD

**Issue by mattico** [notriddle/ammonia#93]
Don't want to pester you, but I'd appreciate a release with my recent changes. You'll be doing your part to finally get [search in the rust book](https://github.com/rust-lang-nursery/mdBook/pull/604) 😄.

**Comment by notriddle** [comment]
It'll be 1.1, since it's adding a new feature, but other than that, sure!

**Comment by notriddle** [comment]
@mattico

It's been released!
