### ISSUE TITLE
Ability to make context-sensitive URL filtering

### ISSUE THREAD

**Issue by kornelski** [notriddle/ammonia#95]
`UrlRelativeEvaluate` is not aware of what kind of URL it is filtering. I need to rewrite image URLs `<img src>` differently than regular `<a href>` links.

Ideally I'd like to also filter absolute image URLs in order to force all images to load via a caching/anonymizing server for privacy. This is somewhat related to #59, but instead of blocking of image URLs I'd like to change them (and only image URLs, links aren't a problem for my use case).

A callback function that gets name of element and attribute would work for me.

**Comment by notriddle** [comment]
You're going to need to add another variant (something like `UrlRelativeTagEvaluate`). The current version (without the tag parameter) will, then, be removed in 2.0.

**Comment by kornelski** [comment]
Could this be generalized to `UrlEvaluate`?

**Comment by notriddle** [comment]
Now that you bring it up ... that's a good point. Your use case does require you to be able to preprocess all of the URLs, not just some of them.

So, yeah, this is completely separate from relative URL evaluation. So, there shouldn't be any deprecation or anything. Just a completely separate hook for URL postprocessing (which would run after relative URL evaluation) that is what you want to use for your camo links.
